CREATE TABLE `speakers` (
	`bio` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`company` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`position` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`social_media` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`id` BIGINT NOT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	CONSTRAINT `FKj0kuu96nhmhc2wvouj51ch4g8` FOREIGN KEY (`id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)