spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_DOCKER_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          audiences: setec-front
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  flyway:
    ignore-migration-patterns: "*:missing"
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  address: ${SERVER_ADDRESS}
  port: ${SERVER_PORT}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

firebase:
  credentials: ${FIREBASE_CREDENTIALS}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2: DEBUG
